server:
  host: "0.0.0.0"
  port: "8080"
  read_timeout: 30
  write_timeout: 30

database:
  host: "beacondb"
  port: 5432
  user: "beacon"
  password: "beacon"
  database: "beacon_db"
  ssl_mode: "disable"

redis:
  host: "beaconcache"
  port: 6379
  password: ""
  database: 0

chain:
  beacon_url: "http://172.17.0.1:3500"
  geth_url: "http://172.17.0.1:8545"

log:
  level: "debug"
